# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 27d97c2cdc5fbd1a1340049abf1740b89d536affe0f765cc417557e6969d92b802fd5a252559b44bd521c3ff630144a2c5da752adc037565adf519d8b1103241

test:
  secret_key_base: eac1caa8d410f265f0be182f4422e5c5ab530b181cafac366c6ad50c31ddfde752d95416746f8e124b3a46c0477703ea5d4b747349002149b598733bdd6b8861

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
